package envfile

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/nandub/dockyard/internal/values"
)

type TemplateOptions struct {
	ValuesFile    string
	Prefix        string
	SensitiveOnly bool
}

type CheckFinding struct {
	Line    int
	Key     string
	Message string
}

func GenerateTemplate(packageDir string, opts TemplateOptions) ([]byte, error) {
	vals, err := values.LoadValues(packageDir, opts.ValuesFile)
	if err != nil {
		return nil, err
	}

	flat := flattenValues("", vals)
	keys := make([]string, 0, len(flat))
	for key := range flat {
		if opts.SensitiveOnly && !IsSensitiveKey(key) {
			continue
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by Dockyard.\n")
	b.WriteString("# Keep real production .env files private and out of source control.\n")
	b.WriteString("# Prefer CI/CD secrets or a dedicated secret manager for production.\n\n")

	for idx, key := range keys {
		if idx > 0 {
			b.WriteString("\n")
		}
		envName := EnvName(opts.Prefix, key)
		if IsSensitiveKey(key) {
			b.WriteString("# Sensitive value. Set this in your shell, CI secrets, or a private .env file.\n")
			b.WriteString(envName)
			b.WriteString("=\n")
			continue
		}
		b.WriteString(envName)
		b.WriteString("=")
		b.WriteString(formatEnvValue(flat[key]))
		b.WriteString("\n")
	}

	return []byte(b.String()), nil
}

func CheckFile(path string) ([]CheckFinding, error) {
	file, err := os.Open(filepath.Clean(path))
	if err != nil {
		return nil, fmt.Errorf("open env file: %w", err)
	}
	defer file.Close()

	seen := map[string]int{}
	var findings []CheckFinding

	scanner := bufio.NewScanner(file)
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "export ") {
			line = strings.TrimSpace(strings.TrimPrefix(line, "export "))
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			findings = append(findings, CheckFinding{
				Line:    lineNumber,
				Message: "line is not KEY=VALUE format",
			})
			continue
		}
		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		if key == "" || !validEnvName(key) {
			findings = append(findings, CheckFinding{
				Line:    lineNumber,
				Key:     key,
				Message: "invalid environment variable name",
			})
			continue
		}
		if previous, exists := seen[key]; exists {
			findings = append(findings, CheckFinding{
				Line:    lineNumber,
				Key:     key,
				Message: fmt.Sprintf("duplicate key; first defined on line %d", previous),
			})
		}
		seen[key] = lineNumber

		if IsSensitiveKey(key) && value != "" && !isPlaceholderValue(value) {
			findings = append(findings, CheckFinding{
				Line:    lineNumber,
				Key:     key,
				Message: "secret-like key has a populated value; keep production env files private",
			})
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read env file: %w", err)
	}
	return findings, nil
}

func EnvName(prefix string, path string) string {
	var b strings.Builder
	prefix = strings.TrimSpace(prefix)
	if prefix != "" {
		b.WriteString(sanitizeEnvSegment(prefix))
		b.WriteString("_")
	}
	parts := strings.FieldsFunc(path, func(r rune) bool {
		return r == '.' || r == '-' || r == ' '
	})
	for idx, part := range parts {
		if idx > 0 {
			b.WriteString("_")
		}
		b.WriteString(sanitizeEnvSegment(part))
	}
	out := b.String()
	if out == "" {
		return "VALUE"
	}
	if out[0] >= '0' && out[0] <= '9' {
		return "_" + out
	}
	return out
}

func IsSensitiveKey(key string) bool {
	lower := strings.ToLower(key)
	needles := []string{"password", "passwd", "secret", "token", "api_key", "apikey", "private_key", "credential", "key"}
	for _, needle := range needles {
		if strings.Contains(lower, needle) {
			return true
		}
	}
	return false
}

func flattenValues(prefix string, vals map[string]any) map[string]any {
	result := map[string]any{}
	for key, value := range vals {
		fullKey := key
		if prefix != "" {
			fullKey = prefix + "." + key
		}
		if nested, ok := value.(map[string]any); ok {
			for nestedKey, nestedValue := range flattenValues(fullKey, nested) {
				result[nestedKey] = nestedValue
			}
			continue
		}
		result[fullKey] = value
	}
	return result
}

func sanitizeEnvSegment(value string) string {
	var b strings.Builder
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToUpper(r))
			continue
		}
		b.WriteRune('_')
	}
	out := strings.Trim(b.String(), "_")
	for strings.Contains(out, "__") {
		out = strings.ReplaceAll(out, "__", "_")
	}
	return out
}

func formatEnvValue(value any) string {
	text := strings.TrimSpace(fmt.Sprint(value))
	if text == "" {
		return ""
	}
	text = strings.ReplaceAll(text, "\r", "")
	text = strings.ReplaceAll(text, "\n", "\\n")
	if strings.ContainsAny(text, " #\"'") {
		return strconvQuote(text)
	}
	return text
}

func strconvQuote(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return `"` + escaped + `"`
}

func validEnvName(key string) bool {
	for idx, r := range key {
		if idx == 0 {
			if r != '_' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}

func isPlaceholderValue(value string) bool {
	value = strings.Trim(value, `"'`)
	lower := strings.ToLower(value)
	return lower == "changeme" ||
		lower == "change-me" ||
		strings.Contains(lower, "replace") ||
		strings.Contains(lower, "example") ||
		(strings.HasPrefix(value, "${") && strings.HasSuffix(value, "}"))
}
