name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod tidy
      - run: gofmt -w ./cmd ./internal
      - run: git diff --exit-code
      - run: go test ./...
      - run: go build -o bin/dockyard ./cmd/dockyard
